/*Creacion de Tablas*/
CREATE TABLE USUARIO (
    No_Identificacion INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Nombre VARCHAR(150),
    Apellido VARCHAR(150),
    Clave_Acceso VARCHAR(150),
    Correo VARCHAR(150),
    Telefono INTEGER,
    Fotografia VARCHAR(150),
    Genero VARCHAR(150),
    fecha_Nacimiento VARCHAR(100),
    fecha_Registro VARCHAR(100),
    Direccion VARCHAR(150),
    Credito_Disponible INTEGER,
    Ganancia_Obtenida INTEGER,
    Clase_Cliente VARCHAR(150),
    Estado VARCHAR(150),
    FK_Rol INTEGER
);
CREATE TABLE ROL (
    Id_Rol INTEGER NOT NULL,
    Descripcion VARCHAR(150)
);
CREATE TABLE BITACORA(
    Id_Bitacora INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Usuario VARCHAR(150),
    Fecha VARCHAR(150),
    Contenido VARCHAR(150)
);
CREATE TABLE CALIFICACION (
    Id_Calificacion INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Id_Usuario INTEGER,
    Calificacion INTEGER,
    Descripcion VARCHAR(150)
);
CREATE TABLE PRODUCTO (
    Id_Producto INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Imagen VARCHAR(150),
    Descripcion VARCHAR(150),
    Id_Categoria INTEGER,
    Precio INTEGER,
    Fecha VARCHAR(150),
    Cantidad INTEGER,
    CantidadDisponible INTEGER,
    Color VARCHAR(150),
    Id_Usuario INTEGER
);
CREATE TABLE CATEGORIA (
    Id_Categoria INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Nombre VARCHAR(150),
    Descripcion VARCHAR(150),
    Estado VARCHAR(150),
    Fk_Categoria INTEGER
);
CREATE TABLE COMENTARIO (
    Id_Comentario INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Id_Producto INTEGER,
    Calificacion VARCHAR(150),
    Comentario VARCHAR(150)
);
/*Insertar un valor de prueba*/
INSERT INTO USUARIO (NOMBRE, APELLIDO, CLAVE_ACCESO, CORREO, TELEFONO, FOTOGRAFIA, GENERO, FECHA_NACIMIENTO, FECHA_REGISTRO, DIRECCION, CREDITO_DISPONIBLE, GANANCIA_OBTENIDA, CLASE_CLIENTE, ESTADO, FK_ROL) VALUES ('Nuevo', 'Nuevo2', '4321', 'noti@gmail.com', '987654321', 'RutaIMG', 'F', '2020-04-17', '2020-04-09', 'casa', '10', '10', 'oro', 'Desconectado','3');
INSERT INTO "PROYECTO2"."USUARIO" (NOMBRE, APELLIDO, CLAVE_ACCESO, CORREO, TELEFONO, FOTOGRAFIA, GENERO, FECHA_NACIMIENTO, FECHA_REGISTRO, DIRECCION, CREDITO_DISPONIBLE, GANANCIA_OBTENIDA, CLASE_CLIENTE, ESTADO, FK_ROL) VALUES ('Cliente Prueba 4', 'Cleinte Prueba 4', 'Cliente4!', 'cliente4@gmail.com', '39335592', '../Frontend/src/assets/PQzkrQXvm3locbg1wRVsDlIr.png', 'Femenino', '1/12/1901', '26/3/2020', 'Izabal', '500', '0', 'Bronce', 'Desconectado', '1')
INSERT INTO "PROYECTO2"."PRODUCTO" (DESCRIPCION, ID_CATEGORIA, PRECIO, FECHA, CANTIDAD, CANTIDADDISPONIBLE, COLOR, ID_USUARIO) VALUES ('Prueba7', '23', '12', '2/3/2020', '100', '1100', 'Verde', '161');
INSERT INTO "PROYECTO2"."PRODUCTO" (DESCRIPCION, ID_CATEGORIA, PRECIO, FECHA, CANTIDAD, CANTIDADDISPONIBLE, COLOR, ID_USUARIO) VALUES ('Prueba8', '23', '12', '2/3/2020', '100', '1100', 'Verde', '161');
INSERT INTO "PROYECTO2"."PRODUCTO" (DESCRIPCION, ID_CATEGORIA, PRECIO, FECHA, CANTIDAD, CANTIDADDISPONIBLE, COLOR, ID_USUARIO) VALUES ('Prueba9', '23', '12', '2/3/2020', '100', '1100', 'Verde', '161');
INSERT INTO "PROYECTO2"."PRODUCTO" (DESCRIPCION, ID_CATEGORIA, PRECIO, FECHA, CANTIDAD, CANTIDADDISPONIBLE, COLOR, ID_USUARIO) VALUES ('Prueba10', '23', '12', '2/3/2020', '100', '1100', 'Verde', '161');
/*Actualizar Contraseña*/
UPDATE USUARIO SET CLAVE_ACCESO = 'Cambio111!' WHERE CORREO ='selvin.lisandro@gmail.com' AND CLAVE_ACCESO='Cambio223';

/*Insertar Roles*/
INSERT INTO ROL(ID_ROL,DESCRIPCION) VALUES ('1','Administrador');
INSERT INTO ROL(ID_ROL,DESCRIPCION) VALUES ('2','Servicio de Ayuda');
INSERT INTO ROL(ID_ROL,DESCRIPCION) VALUES ('3','Usuario');


/*Busqueda*/
SELECT * FROM USUARIO;
/*Reportes de Administrador*/
SELECT * FROM USUARIO WHERE FK_ROL=2 AND GENERO='Masculino';
SELECT * FROM USUARIO WHERE FK_ROL=3 AND GENERO='Femenino';

SELECT usuario.nombre,AVG(calificacion.calificacion) FROM calificacion,usuario 
WHERE usuario.no_identificacion=calificacion.id_usuario
GROUP BY usuario.nombre

SELECT usuario.nombre,COUNT(producto.id_categoria) FROM producto,usuario
WHERE usuario.no_identificacion=producto.id_usuario 
GROUP BY usuario.nombre
ORDER BY COUNT(producto.id_categoria) DESC
FETCH FIRST 3 ROWS ONLY;

SELECT producto.descripcion, categoria.nombre FROM categoria, producto
WHERE producto.id_categoria=categoria.id_categoria

SELECT producto.descripcion,COUNT(comentario),producto.fecha FROM COMENTARIO,PRODUCTO 
WHERE producto.id_producto=comentario.id_producto
GROUP BY producto.descripcion, producto.fecha

SELECT producto.descripcion,AVG(comentario.calificacion) FROM producto,comentario
WHERE producto.id_producto=comentario.id_producto 
GROUP BY producto.descripcion
ORDER BY AVG(comentario.calificacion) ASC
FETCH FIRST 3 ROWS ONLY;

/*Eliiniar Tabla*/
DROP TABLE USUARIO;
DROP TABLE PRODUCTO;
DROP TABLE ROL;
DROP TABLE BITACORA;
DROP TABLE CALIFICACION;
DROP TABLE CATEGORIA;
/*Version de oracle*/
select * from v$version where banner like 'Oracle%';